# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b4c84af35d465cee509cf9e0ee89cf93e9122ffe8d96980f385999f3dc948dd0d335f4d59c5fd5bdc0af5c41c95f800c494a0e9a054d9711fcfe6469686d05

test:
  secret_key_base: b3e1c412d3c341e17e1ae4e3e907c6ed565fe8ee326423cc8589453c77d3ceaf7575f3bfbb2ec2027787d18e465e7b2f0210959d8a18466f7db6e37f9454cbd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
